In [1]:
import requests
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

print("All imports worked")

All imports worked

In [2]:
API_KEY = "1325021c1b821b740bfb0bd7b0a1b613"

In [3]:
movie_name = "Interstellar"

url = "https://api.themoviedb.org/3/search/movie"

params = {
    "api_key": API_KEY,
    "query": movie_name
}

response = requests.get(url, params=params)
data = response.json()

data

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 65.2549,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.473,
   'vote_count': 39685},
  {'adult': False,
   'backdrop_path': '/z7JUwll8F1BSVc8NjVGelW87mcU.jpg',
   'genre_ids': [99],
   'id': 529107,
   'title': "Inside 'Interstellar'",
   'original_language': 'en',
   'original_title': "Inside 'Interstellar'",
   'overview': 'Cast and crew of Christopher Nolan\'s "Interstellar" discuss project origins, the film\'s imagery, ambitions, incorporating IMAX footage, the human element within the film, arm shooting locations outside of Calgary, the set construction and design, working with real corn, mechanical characters, including backstory, design, the blend of practical and digital effects in bringing them to life, the differences in the characters, the human performances behind the characters, the creative process behind the film\'s music, Icelandic locations, vehicle interiors, the processes of simulating the absence of gravity, the crucial end-film visuals and influence and inspiration for future generations',
   'popularity': 1.056,
   'poster_path': '/xWA7Bbo9VeahPcKCFYiC7NZXNoV.jpg',
   'release_date': '2015-03-31',
   'softcore': False,
   'video': False,
   'vote_average': 6.917,
   'vote_count': 12},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [35],
   'id': 287954,
   'title': 'Lolita from Interstellar Space',
   'original_language': 'en',
   'original_title': 'Lolita from Interstellar Space',
   'overview': 'An undeniably beautiful alien is sent to Earth to study the complex mating rituals of human beings, which leads to the young interstellar traveler experiencing the passion that surrounds the centuries-old ritual of the species.',
   'popularity': 1.1307,
   'poster_path': '/nhWlip1s5YzhRFKGlHABGJrBhZn.jpg',
   'release_date': '2014-03-08',
   'softcore': False,
   'video': False,
   'vote_average': 5.0,
   'vote_count': 15},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [99, 10770],
   'id': 301959,
   'title': "Interstellar: Nolan's Odyssey",
   'original_language': 'en',
   'original_title': "Interstellar: Nolan's Odyssey",
   'overview': "A look behind the lens of Christopher Nolan's space epic.",
   'popularity': 1.4189,
   'poster_path': '/i4PpBcuLvdcJwIf3hkcV9QDR1iH.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 7.763,
   'vote_count': 186},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [28],
   'id': 649745,
   'title': 'Interstellar Wandering',
   'original_language': 'zh',
   'original_title': '星际流浪',
   'overview': 'The film tells that the catastrophe era, the earth is a waste land, the survivors are divided into wanderers and civilians, they are attached to the rule of the interstellar armed groups, in which the rogues rely on the plundering of civilian materials as a livelihood, making civilians in this harsh It is difficult to survive in the environment. After a hundred years of black technology explosion, it will bring about a civilized renaissance. In the face of the deteriorating planet, mankind is determined to continue the race and is determined to interstellar immigration. The "curvature engine" developed by the Chinese researcher Hailei has become the key to the interstellar immigration, and is also the target of robbers and interstellar armed groups.',
   'popularity': 0.3373,
   'poster_path': '/oUWDbde5bWu9syBZglWDIwB1SPm.jpg',
   'release_date': '2019-08-02',
   'softcore': False,
   'video': False,
   'vote_average': 2.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': '/8C32MMrMYT5gON7nXgEGeM4puH4.jpg',
   'genre_ids': [99],
   'id': 336592,
   'title': 'The Science of Interstellar',
   'original_language': 'en',
   'original_title': 'The Science of Interstellar',
   'overview': "Matthew McConaughey narrates a fascinating look at Christopher Nolan's sci-fi film, 'Interstellar', including scientific foundations, the work of consulting Scientist Kip Thorne, basic film themes, the science behind the search for planets capable of hosting life, space-time and the theory of relativity, the science of wormholes and black holes, crafting the film's visuals based on real scientific observation, the birth of the universe, the Dust Bowl and the evolution of dust as a toxin, the likelihood of future dust storms, the prospects of escaping a dying or doomed planet and the possibilities of colonizing Mars.",
   'popularity': 1.0007,
   'poster_path': '/pUvbuOTHKQWrLuGY1x2pHd1evPL.jpg',
   'release_date': '2014-11-13',
   'softcore': False,
   'video': False,
   'vote_average': 6.9,
   'vote_count': 35},
  {'adult': False,
   'backdrop_path': '/wUZID3WzrzuIQmcIjXahZkV1ItI.jpg',
   'genre_ids': [878],
   'id': 398188,
   'title': 'Interstellar Wars',
   'original_language': 'en',
   'original_title': 'Interstellar Wars',
   'overview': 'For millennia the Alien force has watched and waited, a brooding menace that has now at last decided to take over the Earth. Communications systems worldwide are sent into chaos by a strange atmospheric interference, a massive spaceship heads towards Earth and smaller spaceships begin to cover entire cities. Suddenly, the wonder turns into horror as the spaceships destroy the cities with energy weapons. When the world counterattacks, the alien ships are invincible to military weapons.  The survivors have to use their wits to kill the aliens, or die.',
   'popularity': 0.2633,
   'poster_path': '/4uWZ8cdrXMLiyLNgdmqQCIM6z40.jpg',
   'release_date': '2016-06-09',
   'softcore': False,
   'video': False,
   'vote_average': 3.0,
   'vote_count': 14},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [878, 16],
   'id': 1443305,
   'title': 'Container Interstellar',
   'original_language': 'de',
   'original_title': 'Container Interstellar',
   'overview': 'Director Helmut Herbst’s animated sci-fi short with characters that would be more fully explored in CATHEDRAL OF NEW EMOTIONS.',
   'popularity': 0.0143,
   'poster_path': '/dp7ch6CGdNnNpcidyzBaFabmEJW.jpg',
   'release_date': '2001-01-01',
   'softcore': False,
   'video': False,
   'vote_average': 7.5,
   'vote_count': 2},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [16, 878],
   'id': 1391726,
   'title': 'Interstellar Stella',
   'original_language': 'en',
   'original_title': 'Interstellar Stella',
   'overview': 'In a world formed by the spectacle of perfect illusions, the king of mediation travels through the lens to fight an anti-image cult that threatens a new generation.',
   'popularity': 0.0193,
   'poster_path': None,
   'release_date': '2006-12-11',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [53, 878],
   'id': 1282990,
   'title': 'Interstellar Interference',
   'original_language': 'en',
   'original_title': 'Interstellar Interference',
   'overview': "During a calm lil hang at Mike's crib, the boys finds themselves facing an unimaginable terror when an otherworldly intruder breaches their sanctuary. As the night unfolds, paranoia grips the group as they realize the sinister intentions of their unwelcome guest. With each passing moment, the line between survival and demise blurs, forcing them to confront their deepest fears and fight for their lives against an entity that knows no mercy. In this heart-pounding thriller, every shadow holds a deadly secret, and every corner hides a chilling revelation as the battle for survival unfolds in the most unexpected of places.",
   'popularity': 0.0495,
   'poster_path': '/2yHZyjf9DC2y2wsOckiTmn7ZJLp.jpg',
   'release_date': '2023-04-22',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [],
   'id': 1450827,
   'title': 'Interstellar Political Prisoner',
   'original_language': 'en',
   'original_title': 'Interstellar Political Prisoner',
   'overview': 'I am Kepler, an exile from the planet Guarding. A long time ago, I asked myself a question: "What am I?" Since then, I began a long search for the meaning of my existence. When I finally got the answer, the day of exile was approaching...',
   'popularity': 0.0239,
   'poster_path': '/1A0wLpRmpMLaoDRGhzvctyeoogp.jpg',
   'release_date': '2016-09-25',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [],
   'id': 1642987,
   'title': 'Primus Interstellar Drum Derby',
   'original_language': 'en',
   'original_title': 'Primus Interstellar Drum Derby',
   'overview': 'In late 2024, the mind boggling and undefinable rock band Primus found themselves in search of a drummer. They scoured the galaxy for the greatest drummers available. After over 6100 eager submissions, this is what they narrowed it down to. Welcome to the Primus Interstellar Drum Derby.',
   'popularity': 0.0466,
   'poster_path': '/l4u0AIIdZUXPQGj8ZpZXYZ8Xt2B.jpg',
   'release_date': '2025-02-20',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': '/lQS9il7YqGjmmBefZY27uG5wbzT.jpg',
   'genre_ids': [99],
   'id': 660698,
   'title': 'Faster Than Light: the Dream of Interstellar Flight',
   'original_language': 'en',
   'original_title': 'Faster Than Light: the Dream of Interstellar Flight',
   'overview': '“Faster Than Light” explores the longstanding quest to develop spacecraft with enough power and speed to reach the stars. The film asks: What will it take to reach a newly discovered planet circling our Sun’s nearest neighbor, Proxima Centauri? Based on real science and engineering, “Faster Than Light” takes audiences on a thrilling journey into the future, aboard laser-driven space sails, antimatter engines, and even warp drive – right out of science fiction. “Who can say how far, and how fast, our technology will one day take us?” said director Thomas Lucas.',
   'popularity': 0.3242,
   'poster_path': '/mbgJxB70uMFK2H8DXHUj5lAMgXx.jpg',
   'release_date': '2017-06-07',
   'softcore': False,
   'video': False,
   'vote_average': 6.4,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [28, 14, 878],
   'id': 460616,
   'title': 'Interstellar Civil War: Shadows of the Empire',
   'original_language': 'en',
   'original_title': 'Interstellar Civil War: Shadows of the Empire',
   'overview': "The Imperial Empire is attacked by an Alliance of rebels led by fanatical mystics. The ruler, Empress Nobu, the 8th generation of her family, wants to execute a bold plan to rescue a cyborg, Leah C6, trapped on the battle ravaged planet Endor. The Empress believes Leah C6 holds the secret to destroying the Alliance of Rebels before their insurgency can kill millions of citizens of the Empire. She recruits her heroic fleet commander, Lord General Luka Raan and asks him to gather a team from the Empire's elite soldiers, the Galactic Rangers. Raan assembles the team in the ruins of Endor which was attacked by depraved Rebels and outlaws led by, Kindo-Ker, a fanatical mystic in Dark Energy. The Galactic Rangers begin a desperate search to find and rescue Leah C6 before the Alliance Rebels can.",
   'popularity': 0.305,
   'poster_path': '/1lDY7ZpEKOl3OaIQURjRbmFPfT8.jpg',
   'release_date': '2017-03-18',
   'softcore': False,
   'video': False,
   'vote_average': 3.1,
   'vote_count': 4},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [35, 18],
   'id': 716603,
   'title': 'Only Interstellar Pinball Lives Forever',
   'original_language': 'en',
   'original_title': 'Only Interstellar Pinball Lives Forever',
   'overview': "A young boy (played by an actual re-purposed Sunday school puppet) loses all faith in religion and afterlife options after having to bury his umpteenth pet, and vows that someday, when he's an adult with money, he'll find a way to become an 'eternal molecule' through science. Then, twenty-two years later, the playing of a pinball game brings dredges up the memory of that vow. Utilizing the hallucinogenic properties of alcohol and cough syrup blends, he undertakes the design of a pinball machine so poignant and dignified that it will convince scientists to create a pinball that we can download our consciousness into and thereby become digitally immortal.",
   'popularity': 0.0388,
   'poster_path': '/uLJMGZlrkmvAO9Ria9zrp8GUqjx.jpg',
   'release_date': '2010-06-28',
   'softcore': False,
   'video': False,
   'vote_average': 7.0,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [12],
   'id': 552531,
   'title': "The Prom Goer's Interstellar Excursion",
   'original_language': 'en',
   'original_title': "The Prom Goer's Interstellar Excursion",
   'overview': 'High schooler Bennett lands the prom date of his dreams, Sophie, just days before the dance. Not long after, he witnesses Sophie being abducted by aliens in the middle of the New Mexico desert.',
   'popularity': 0.0633,
   'poster_path': None,
   'release_date': '',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [99, 36],
   'id': 1573960,
   'title': 'Shouting at Stars: A History of Interstellar Messages',
   'original_language': 'en',
   'original_title': 'Shouting at Stars: A History of Interstellar Messages',
   'overview': 'Since the early 1970s, humanity has sent messages beyond the Solar System in the hopes of contacting another civilization. Some were physically attached to interstellar spacecraft, while others were beamed into space in the form of radio signals. This documentary provides a detailed chronology of almost all of these messages with a focus on their meaning and improbability of reception',
   'popularity': 0.0478,
   'poster_path': '/hrRuQbG7UE0LD3EktofTR5N7QPM.jpg',
   'release_date': '2025-10-31',
   'softcore': False,
   'video': False,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [99],
   'id': 763179,
   'title': 'Cosmic Journey: The Voyager Interstellar Mission and Message',
   'original_language': 'en',
   'original_title': 'Cosmic Journey: The Voyager Interstellar Mission and Message',
   'overview': 'The farthest Voyager: "Cosmic Journey," a documentary premiering on the A&E cable network, tells the saga of the farthest-flung space journey to date - the Voyager interstellar mission, which started out 25 years ago and sailed past Jupiter, Saturn, Uranus and Neptune in the 1980s.',
   'popularity': 0.1084,
   'poster_path': None,
   'release_date': '2003-01-16',
   'softcore': False,
   'video': False,
   'vote_average': 2.5,
   'vote_count': 1},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [],
   'id': 1501040,
   'title': 'The Future is Now: A Look Back at Interstellar',
   'original_language': 'en',
   'original_title': 'The Future is Now: A Look Back at Interstellar',
   'overview': 'A brief (23 minutes) retrospective on the film, but what it lacks in length it makes up for with insight. Featuring input from key collaborators like producer Emma Thomas, co-writer Jonathan Nolan, cinematographer Hoyle van Hoytema, co-producer Kip Thorne, and Interstellar admirers like Denis Villnevue, Peter Jackson, critic Kenneth Turan, Josh Hartnett, this is a mostly standard look back, but if you’re in this movie’s choir you’ll enjoy the preaching.',
   'popularity': 0.0535,
   'poster_path': None,
   'release_date': '2024-12-10',
   'softcore': False,
   'video': True,
   'vote_average': 0.0,
   'vote_count': 0},
  {'adult': False,
   'backdrop_path': None,
   'genre_ids': [],
   'id': 986255,
   'title': 'How to Colonize the Stars: The Challenge of Interstellar Flight',
   'original_language': 'en',
   'original_title': 'How to Colonize the Stars: The Challenge of Interstellar Flight',
   'overview': "Leading physicists and engineers in the field of interstellar travel discuss some of the deep issues we face when considering the problem of sending spacecraft to other stars. Will mankind ever truly become a space fairing civilization? Space colonization is no longer the fodder of science fiction, it is becoming a reality. We'll need to learn how to grow food, manufacture and live off our planet.",
   'popularity': 0.0143,
   'poster_path': '/ddYoMPJioxY7qQxt7JyUaLCWMjw.jpg',
   'release_date': '2009-06-09',
   'softcore': False,
   'video': False,
   'vote_average': 10.0,
   'vote_count': 1}],
 'total_pages': 2,
 'total_results': 27}

In [4]:
first_movie = data["results"][0]

print(first_movie["title"])
print(first_movie["overview"])
print(first_movie["release_date"])
print(first_movie["vote_average"])

Interstellar
The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.
2014-11-05
8.473

In [5]:
from IPython.display import Image, display

poster_path = first_movie["poster_path"]
poster_url = "https://image.tmdb.org/t/p/w500" + poster_path

print(poster_url)
display(Image(url=poster_url))

https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg

In [6]:
movie_id = first_movie["id"]

print(movie_id)

157336

In [7]:
recommend_url = f"https://api.themoviedb.org/3/movie/{movie_id}/recommendations"

params = {
    "api_key": API_KEY
}

response = requests.get(recommend_url, params=params)
recommend_data = response.json()

recommend_data

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/n7p6UTAZtkeoHkwCO42BEQaMFJY.jpg',
   'id': 644,
   'title': 'A.I. Artificial Intelligence',
   'original_title': 'A.I. Artificial Intelligence',
   'overview': 'David, a robotic boy—the first of his kind programmed to love—is adopted as a test case by a Cybertronics employee and his wife. Though he gradually becomes their child, a series of unexpected circumstances make this life impossible for David.',
   'poster_path': '/8MZSGX5JORoO72EfuAEcejH5yHn.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 878, 12],
   'popularity': 6.8784,
   'release_date': '2001-06-29',
   'softcore': False,
   'video': False,
   'vote_average': 7.054,
   'vote_count': 6642},
  {'adult': False,
   'backdrop_path': '/iQcCAm8hKWZyUntqrvzyEGtXyJl.jpg',
   'id': 670292,
   'title': 'The Creator',
   'original_title': 'The Creator',
   'overview': 'Amid a future war between the human race and the forces of artificial intelligence, a hardened ex-special forces agent grieving the disappearance of his wife, is recruited to hunt down and kill the Creator, the elusive architect of advanced AI who has developed a mysterious weapon with the power to end the war—and mankind itself.',
   'poster_path': '/3dSivDtOuyxLDxPH4v2tcNG1fP7.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 28, 12],
   'popularity': 7.9614,
   'release_date': '2023-09-27',
   'softcore': False,
   'video': False,
   'vote_average': 7.012,
   'vote_count': 3807},
  {'adult': False,
   'backdrop_path': '/cqXEwYFcwyKPZCKl1jAPaG3cMsl.jpg',
   'id': 13475,
   'title': 'Star Trek',
   'original_title': 'Star Trek',
   'overview': 'The fate of the galaxy rests in the hands of bitter rivals. One, James Kirk, is a delinquent, thrill-seeking Iowa farm boy. The other, Spock, a Vulcan, was raised in a logic-based society that rejects all emotion. As fiery instinct clashes with calm reason, their unlikely but powerful partnership is the only thing capable of leading their crew through unimaginable danger, boldly going where no one has gone before. The human adventure has begun again.',
   'poster_path': '/hN2ZtF3Uw6mhIHZiqL0SKzELtKn.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 28, 12],
   'popularity': 8.3945,
   'release_date': '2009-05-06',
   'softcore': False,
   'video': False,
   'vote_average': 7.43,
   'vote_count': 10466},
  {'adult': False,
   'backdrop_path': '/y8ZholsWIn4jR3JoDWOSSFY87vf.jpg',
   'id': 585378,
   'title': 'After Yang',
   'original_title': 'After Yang',
   'overview': "When his young daughter's beloved companion — an android named Yang — malfunctions, Jake searches for a way to repair him. In the process, Jake discovers the life that has been passing in front of him, reconnecting with his wife and daughter across a distance he didn't know was there.",
   'poster_path': '/qjEuDeKOhA7JqaaqhLSfoS9titb.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 18],
   'popularity': 2.7681,
   'release_date': '2022-03-04',
   'softcore': False,
   'video': False,
   'vote_average': 6.401,
   'vote_count': 509},
  {'adult': False,
   'backdrop_path': '/hPHahVM3JDlE0Zexu6avavypk0g.jpg',
   'id': 13001,
   'title': 'Stargate: The Ark of Truth',
   'original_title': 'Stargate: The Ark of Truth',
   'overview': "SG-1 searches for an ancient weapon which could help them defeat the Ori, and discover it may be in the Ori's own home galaxy. As the Ori prepare to send ships through to the Milky Way to attack Earth, SG-1 travels to the Ori galaxy aboard the Odyssey. The International Oversight committee have their own plans and SG-1 finds themselves in a distant galaxy fighting two powerful enemies.",
   'poster_path': '/kIqsCdZBmKYuPwaDnrFYzK1gqlM.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 12, 878],
   'popularity': 1.9921,
   'release_date': '2008-03-11',
   'softcore': False,
   'video': False,
   'vote_average': 7.089,
   'vote_count': 568},
  {'adult': False,
   'backdrop_path': '/rPaOAtK6OpnHQ9r61WPM4WWNxaH.jpg',
   'id': 152,
   'title': 'Star Trek: The Motion Picture',
   'original_title': 'Star Trek: The Motion Picture',
   'overview': 'When an unidentified alien destroys three powerful Klingon cruisers, Captain James T. Kirk returns to the newly transformed U.S.S. Enterprise to take command.',
   'poster_path': '/wfiAfNwH6CMKxz4vRaW8CPTabtk.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 12, 9648],
   'popularity': 3.3326,
   'release_date': '1979-12-07',
   'softcore': False,
   'video': False,
   'vote_average': 6.484,
   'vote_count': 1921},
  {'adult': False,
   'backdrop_path': '/w1Z1I9PqTK5UjG6RVAFXLCjp1Sw.jpg',
   'id': 434853,
   'title': 'Space/Time',
   'original_title': 'Space/Time',
   'overview': 'After a fatal test shuts down their project, a disgraced team of scientists enters the criminal underworld to rebuild a forbidden space-bending engine that could rescue humanity or annihilate it entirely.',
   'poster_path': '/uje1ecKMnNpZp0at5TxlvVgVXqI.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 28, 53],
   'popularity': 4.8003,
   'release_date': '2025-06-25',
   'softcore': False,
   'video': False,
   'vote_average': 6.0,
   'vote_count': 54},
  {'adult': False,
   'backdrop_path': '/vIEuJiIZN9EclAJDmD49F2zUzuX.jpg',
   'id': 274855,
   'title': 'Geostorm',
   'original_title': 'Geostorm',
   'overview': "After an unprecedented series of natural disasters threatened the planet, the world's leaders came together to create an intricate network of satellites to control the global climate and keep everyone safe. But now, something has gone wrong: the system built to protect Earth is attacking it, and it becomes a race against the clock to uncover the real threat before a worldwide geostorm wipes out everything and everyone along with it.",
   'poster_path': '/nrsx0jEaBgXq4PWo7SooSnYJTv.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 878, 53],
   'popularity': 5.8816,
   'release_date': '2017-10-12',
   'softcore': False,
   'video': False,
   'vote_average': 6.116,
   'vote_count': 5151},
  {'adult': False,
   'backdrop_path': '/zzhXcdGij5MPfrnpNoC6dKhgT8M.jpg',
   'id': 2267,
   'title': 'The Last Mimzy',
   'original_title': 'The Last Mimzy',
   'overview': 'Two siblings begin to develop special talents after they find a mysterious box of toys, and soon their parents and even their teacher are drawn into a strange new world – and find a task ahead of them that is far more important than any of them could imagine.',
   'poster_path': '/jnLXcQFx4hSKDNG1P6RMz4v5jje.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 878, 12],
   'popularity': 1.732,
   'release_date': '2007-02-09',
   'softcore': False,
   'video': False,
   'vote_average': 6.356,
   'vote_count': 486},
  {'adult': False,
   'backdrop_path': '/8esvgUVVX4GGXLGuGvKDYFNqVdt.jpg',
   'id': 10122,
   'title': 'Flight of the Navigator',
   'original_title': 'Flight of the Navigator',
   'overview': "12-year-old David is accidentally knocked out in the forest near his home, but when he awakens eight years have passed. His family is overjoyed to have him back, but is just as perplexed as he is that he hasn't aged. When a NASA scientist discovers a UFO nearby, David gets the chance to unravel the mystery and recover the life he lost.",
   'poster_path': '/tdRgQWMximj0tL6OWu9kRTtePmI.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [10751, 878, 12],
   'popularity': 2.7038,
   'release_date': '1986-07-30',
   'softcore': False,
   'video': False,
   'vote_average': 6.965,
   'vote_count': 940},
  {'adult': False,
   'backdrop_path': '/yxlGeAK6BrbKng8VSJSKTpSXSsL.jpg',
   'id': 14337,
   'title': 'Primer',
   'original_title': 'Primer',
   'overview': 'A group of fledgling inventors discover a complex method to manipulate reality. At first, they successfully game the stock market with it, but the consequences of the invention start to catch up with them.',
   'poster_path': '/xEoq2WmDzpzxhkHEsmOYOg6BPg6.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 18, 53],
   'popularity': 3.3222,
   'release_date': '2004-10-08',
   'softcore': False,
   'video': False,
   'vote_average': 6.76,
   'vote_count': 2409},
  {'adult': False,
   'backdrop_path': '/cBGQMVohebbWfmEGdezjyOdW7MO.jpg',
   'id': 559581,
   'title': 'Stowaway',
   'original_title': 'Stowaway',
   'overview': 'A three-person crew on a mission to Mars faces an impossible choice when an unplanned passenger jeopardizes the lives of everyone on board.',
   'poster_path': '/eFyRjhJfhNgM565U2mwEp5YUUOv.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 18, 53],
   'popularity': 2.9828,
   'release_date': '2021-06-24',
   'softcore': False,
   'video': False,
   'vote_average': 5.992,
   'vote_count': 657},
  {'adult': False,
   'backdrop_path': '/5lUpy6OrDhzdeAGBaM1mIsQvfOl.jpg',
   'id': 157,
   'title': 'Star Trek III: The Search for Spock',
   'original_title': 'Star Trek III: The Search for Spock',
   'overview': "A surprise visit from Spock's father provides a startling revelation: McCoy is harboring Spock's living essence.",
   'poster_path': '/yqEj0oPfKBMCz7YcCARHDgH7VFm.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 28, 12, 53],
   'popularity': 2.4736,
   'release_date': '1984-06-01',
   'softcore': False,
   'video': False,
   'vote_average': 6.586,
   'vote_count': 1510},
  {'adult': False,
   'backdrop_path': '/2n7lYEeIbucsEQCswRcVB6ZYmMP.jpg',
   'id': 777443,
   'title': 'The Electric State',
   'original_title': 'The Electric State',
   'overview': 'An orphaned teen hits the road with a mysterious robot to find her long-lost brother, teaming up with a smuggler and his wisecracking sidekick.',
   'poster_path': '/tn6gDIrQMwHSivF01igLfbggmYD.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 12, 28],
   'popularity': 6.7166,
   'release_date': '2025-03-07',
   'softcore': False,
   'video': False,
   'vote_average': 6.487,
   'vote_count': 1639},
  {'adult': False,
   'backdrop_path': '/kVChi7qHX9UMcpAh7J6fGBCCH2c.jpg',
   'id': 262543,
   'title': 'Automata',
   'original_title': 'Autómata',
   'overview': 'Jacq Vaucan, an insurance agent of ROC robotics corporation, routinely investigates the case of manipulating a robot. What he discovers will have profound consequences for the future of humanity.',
   'poster_path': '/h7SEtIWOfLsuCWhQgflev7ppRPq.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [53, 878],
   'popularity': 5.5195,
   'release_date': '2014-10-09',
   'softcore': False,
   'video': False,
   'vote_average': 5.883,
   'vote_count': 1785},
  {'adult': False,
   'backdrop_path': '/avjG5EPgWXyLvsUId6hEn0iqT4A.jpg',
   'id': 2103,
   'title': 'Solaris',
   'original_title': 'Solaris',
   'overview': 'A troubled psychologist is sent to investigate the crew of an isolated research station orbiting a bizarre planet.',
   'poster_path': '/drdrB1hEZmzFlK1xtW5HMxK3LUJ.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [18, 878, 9648],
   'popularity': 3.2771,
   'release_date': '2002-11-27',
   'softcore': False,
   'video': False,
   'vote_average': 5.9,
   'vote_count': 1441},
  {'adult': False,
   'backdrop_path': '/duengnNbJdTdjR329SmAAJO4stC.jpg',
   'id': 419704,
   'title': 'Ad Astra',
   'original_title': 'Ad Astra',
   'overview': 'The near future, a time when both hope and hardships drive humanity to look to the stars and beyond. While a mysterious phenomenon menaces to destroy life on planet Earth, astronaut Roy McBride undertakes a mission across the immensity of space and its many perils to uncover the truth about a lost expedition that decades before boldly faced emptiness and silence in search of the unknown.',
   'poster_path': '/xBHvZcjRiWyobQ9kxBhO6B2dtRI.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [878, 18],
   'popularity': 2.9764,
   'release_date': '2019-09-17',
   'softcore': False,
   'video': False,
   'vote_average': 6.129,
   'vote_count': 7210},
  {'adult': False,
   'backdrop_path': '/7COZZS8Yfe13pEyjuF4k5WGsLEA.jpg',
   'id': 1687,
   'title': 'Escape from the Planet of the Apes',
   'original_title': 'Escape from the Planet of the Apes',
   'overview': 'The world is shocked by the appearance of three talking chimpanzees, who arrived mysteriously in a spacecraft. Intrigued by their intelligence, humans use them for research - until the apes attempt to escape.',
   'poster_path': '/AnbLVdUEroTfHTUVAJCxkL4R0IH.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 878],
   'popularity': 2.4948,
   'release_date': '1971-05-20',
   'softcore': False,
   'video': False,
   'vote_average': 6.4,
   'vote_count': 1218},
  {'adult': False,
   'backdrop_path': '/s6h8MemlWFshLmPfd08syBpaTTK.jpg',
   'id': 13811,
   'title': 'Knowing',
   'original_title': 'Knowing',
   'overview': "A teacher opens a time capsule that has been dug up at his son's elementary school; in it are some chilling predictions -- some that have already occurred and others that are about to -- that lead him to believe his family plays a role in the events that are about to unfold.",
   'poster_path': '/OG0mxQt4YaNIWiz8EKJSHe9lPh.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [28, 9648, 878, 53],
   'popularity': 7.2595,
   'release_date': '2009-03-19',
   'softcore': False,
   'video': False,
   'vote_average': 6.2,
   'vote_count': 5784},
  {'adult': False,
   'backdrop_path': '/5QTwfS9vcr22Nl7PCcUro7dEMFq.jpg',
   'id': 811,
   'title': 'Silent Running',
   'original_title': 'Silent Running',
   'overview': 'After the entire flora goes extinct, ecologist Lowell maintains a greenhouse aboard a space station for the future with his android companions. However, he rebels after being ordered to destroy the greenhouse in favor of carrying cargo, a decision that puts him at odds with everyone but his mechanical companions.',
   'poster_path': '/ahasZ5HILZHtlrl6cbXgpfk0y8H.jpg',
   'media_type': 'movie',
   'original_language': 'en',
   'genre_ids': [12, 878, 18],
   'popularity': 1.6102,
   'release_date': '1972-03-09',
   'softcore': False,
   'video': False,
   'vote_average': 6.397,
   'vote_count': 638}],
 'total_pages': 30,
 'total_results': 600}

In [8]:
recommendations = recommend_data["results"]

for movie in recommendations[:10]:
    print(movie["title"])

A.I. Artificial Intelligence
The Creator
Star Trek
After Yang
Stargate: The Ark of Truth
Star Trek: The Motion Picture
Space/Time
Geostorm
The Last Mimzy
Flight of the Navigator

In [9]:
movies_list = []

# Add searched movie first
movies_list.append({
    "title": first_movie["title"],
    "overview": first_movie["overview"],
    "release_date": first_movie["release_date"],
    "rating": first_movie["vote_average"]
})

# Add TMDB recommended movies
for movie in recommendations[:10]:
    movies_list.append({
        "title": movie["title"],
        "overview": movie["overview"],
        "release_date": movie.get("release_date", ""),
        "rating": movie["vote_average"]
    })

df = pd.DataFrame(movies_list)

df

,title,overview,release_date,rating
0,Interstellar,The adventures of a group of explorers who mak...,2014-11-05,8.473
1,A.I. Artificial Intelligence,"David, a robotic boy—the first of his kind pro...",2001-06-29,7.054
2,The Creator,Amid a future war between the human race and t...,2023-09-27,7.012
3,Star Trek,The fate of the galaxy rests in the hands of b...,2009-05-06,7.430
4,After Yang,When his young daughter's beloved companion — ...,2022-03-04,6.401
5,Stargate: The Ark of Truth,SG-1 searches for an ancient weapon which coul...,2008-03-11,7.089
6,Star Trek: The Motion Picture,When an unidentified alien destroys three powe...,1979-12-07,6.484
7,Space/Time,"After a fatal test shuts down their project, a...",2025-06-25,6.000
8,Geostorm,After an unprecedented series of natural disas...,2017-10-12,6.116
9,The Last Mimzy,Two siblings begin to develop special talents ...,2007-02-09,6.356
10,Flight of the Navigator,12-year-old David is accidentally knocked out ...,1986-07-30,6.965

In [10]:
df["features"] = (
    df["title"].fillna("") + " " +
    df["overview"].fillna("") + " " +
    df["release_date"].fillna("")
)

df[["title", "features"]]

,title,features
0,Interstellar,Interstellar The adventures of a group of expl...
1,A.I. Artificial Intelligence,"A.I. Artificial Intelligence David, a robotic ..."
2,The Creator,The Creator Amid a future war between the huma...
3,Star Trek,Star Trek The fate of the galaxy rests in the ...
4,After Yang,After Yang When his young daughter's beloved c...
5,Stargate: The Ark of Truth,Stargate: The Ark of Truth SG-1 searches for a...
6,Star Trek: The Motion Picture,Star Trek: The Motion Picture When an unidenti...
7,Space/Time,Space/Time After a fatal test shuts down their...
8,Geostorm,Geostorm After an unprecedented series of natu...
9,The Last Mimzy,The Last Mimzy Two siblings begin to develop s...
10,Flight of the Navigator,Flight of the Navigator 12-year-old David is a...

In [11]:
cv = CountVectorizer(stop_words="english")

vectors = cv.fit_transform(df["features"])

vectors.shape

(11, 280)

In [12]:
similarity = cosine_similarity(vectors)

similarity

array([[1.        , 0.03779645, 0.03123475, 0.058346  , 0.        ,
        0.0246183 , 0.04364358, 0.07844645, 0.        , 0.        ,
        0.        ],
       [0.03779645, 1.        , 0.0885422 , 0.05513178, 0.06579517,
        0.        , 0.        , 0.07412493, 0.03106849, 0.        ,
        0.15328483],
       [0.03123475, 0.0885422 , 1.        , 0.02278028, 0.02718636,
        0.01922366, 0.        , 0.        , 0.02567481, 0.09563651,
        0.        ],
       [0.058346  , 0.05513178, 0.02278028, 1.        , 0.        ,
        0.07181896, 0.15915175, 0.02860648, 0.02398006, 0.        ,
        0.        ],
       [0.        , 0.06579517, 0.02718636, 0.        , 1.        ,
        0.06428243, 0.        , 0.        , 0.        , 0.        ,
        0.05647825],
       [0.0246183 , 0.        , 0.01922366, 0.07181896, 0.06428243,
        1.        , 0.02686077, 0.        , 0.02023612, 0.        ,
        0.01996808],
       [0.04364358, 0.        , 0.        , 0.15915175, 0.        ,
        0.02686077, 1.        , 0.        , 0.0358748 , 0.        ,
        0.07079923],
       [0.07844645, 0.07412493, 0.        , 0.02860648, 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.03106849, 0.02567481, 0.02398006, 0.        ,
        0.02023612, 0.0358748 , 0.        , 1.        , 0.0335578 ,
        0.02666904],
       [0.        , 0.        , 0.09563651, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.0335578 , 1.        ,
        0.        ],
       [0.        , 0.15328483, 0.        , 0.        , 0.05647825,
        0.01996808, 0.07079923, 0.        , 0.02666904, 0.        ,
        1.        ]])

In [13]:
selected_movie_index = 0

scores = list(enumerate(similarity[selected_movie_index]))

scores = sorted(scores, key=lambda x: x[1], reverse=True)

for index, score in scores[1:6]:
    print(df.iloc[index]["title"], "-", score)

Space/Time - 0.07844645405527362
Star Trek - 0.058345996599157825
Star Trek: The Motion Picture - 0.043643578047198484
A.I. Artificial Intelligence - 0.03779644730092272
The Creator - 0.031234752377721216